# Version of Docker-compose
version: '2'
services:
  FrontEnd:
    image: kartiksaxena2000/cloud_airlines_webapp_mac:latest
    container_name: cloud_airlines_webapp
    ports:
      - "3000:80"
    networks:
      - cloud_airlines_net

networks:
  cloud_airlines_net:
    driver: bridge